### PR TITLE
Add new Rule (Date)

### PR DESCRIPTION
**Pull request by refatalsakka**
- Created new Class (Date)
_isInputValid()_ is checking if the date format valid or not using regex.
**_Formats examples_**
[Regex Example](https://regex101.com/r/cRk43k/13)

- Created new ClassTest (DateTest)

### CODE REVIEW

**Comment by refatalsakka** [comment]
`return strtotime($this->getValue()) ? true : false;` can be replace to `return strtotime($this->getValue());`

**Comment by olivervogel** [comment]
Thanks for your contribution. This package was created as an addition to the existing [Laravel Validation Rules](https://laravel.com/docs/8.x/validation). There are already [rules to validate date formats](https://laravel.com/docs/8.x/validation#rule-date). 

I gotta ask, does your rule provide a other/better solution?

**Comment by refatalsakka** [comment]
Bitte schön.

I haven't really worked with Laravel yet. So i can't tell.

**Comment by olivervogel** [comment]
This package is meant as an extension for the Laravel Validator providing more rules. There are already [rules for date validation](https://laravel.com/docs/8.x/validation#rule-date), so I won't merge this.

**Pull request closed without merging**
