### PR TITLE
Fixes and changes for dutch language and postal code

### PR DESCRIPTION
**Pull request by timmeijers**

### CODE REVIEW

**Comment by olivervogel** [comment]
Thanks for your contribution. Unfortunately, the MR makes the tests fail for some NL postal codes.

- `1234` should be valid but returns invalid now.
- `1234AA` should be invalid but is now valid.

Can you tell me more about valid postal codes in the Netherlands?

**Comment by timmeijers** [comment]
Hi Oliver,

Ofcourse!

In the netherlands we use only one format of postal codes which starts with 4 digits and ends with 2 capital letters.

1234AB
In some odd situations we do allow there to be a space between. So thats why i added the \s? To make that optional, like the following
1234 AB

But since i didnt want to force the case sensitive part for people already using this i kept the a-z and the /i

If you want to make it more strict you can do A-Z and remove the case insensitive marker.

If you have any questions, feel free to ask.

Kind regards,
Tim Meijers

________________________________

**Comment by olivervogel** [comment]
Ok, Thanks. I adjusted the tests to meet the format.

**Comment by timmeijers** [comment]
Awesome, tnx!

________________________________

**Pull request merged**
